### ISSUE TITLE
Request: Use system theme in translate dialog

### ISSUE THREAD

**Issue by ghost** [gufoe/text-translator#10]
I love theming and this extension is AMAZING, but could you please make it use the current system theme in the translation dialog? I use [Adapta](https://github.com/adapta-project/adapta-gtk-theme) for my system.

**Comment by gufoe** [comment]
I fear there might be no easy way (I'm not the original author of the extension, and my knowledge about the code is limited), but if you're familiar with CSS you can edit the colors in `.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/stylesheet.css`, shouldn't be too complex.

**Comment by gufoe** [comment]
You might be interested in this:
https://github.com/gufoe/text-translator/issues/15#issuecomment-340013831
