### ISSUE TITLE
receiving null in many translations....

### ISSUE THREAD

**Issue by AntiNSA** [gufoe/text-translator#11]
receiving null in many translations.... I downgraded to keep translation going... receiving null in many translations...

**Comment by gufoe** [comment]
Me aswell, and did downgrading solve the problem?

**Comment by AntiNSA** [comment]
Downgrading from gnome 3.24 allowed the plugin to work again, however I
have a lot of null in the translations.

Robert Eaton ---- TheCenterOfTheNet.com

   - DEEP THOUGHT CYCLE (BIKE COMMUTER BLOG) *LIVE FROM CHINA
   <https://www.youtube.com/channel/UCXZr7oMU0K4Gu5WfaxTaMUg>
   - My Daily Cycle Log @ Strava <https://www.strava.com/athletes/445792>
   - My Work & Passion: <http://www.thecenterofthenet.com>
   - Almost Never Used or Updated <http://cn.linkedin.com/in/roberpteatonjr>
   :
   - My Garmin Connect Commuting Cycling & Swimming (not so much time to
   swim) Blog <https://connect.garmin.com/modern/profile/reaton>


=====================
[SITE INTRO] [1] Welcome to The Center Of The Net Mission Statement Part 1
http://thecenterofthenet.com/faq/site-intro-1-welcome-
center-net-mission-statement-part-1

[SITE INTRO][2] Why Re-Create an Open Learning Resource @ TheCenterOfTheNet
(Mission Statement) Part 2
http://thecenterofthenet.com/faq/site-intro2-why-re-create-
open-learning-resource-thecenterofthenet-mission-statement-part-2

[SITE INTRO][3] Why Think (contribute resources, share thoughts, ideas and
blogs.. etc..) @ TheCenterOfTheNet.com?
http://thecenterofthenet.com/faq/site-intro3-why-think-
contribute-resources-share-thoughts-ideas-and-blogs-etc

[SITE INTRO][4] Why Create Groups/Use Study Groups @ TheCenterOfTheNet.com ?
http://thecenterofthenet.com/faq/site-intro4-why-create-
groupsuse-study-groups-thecenterofthenetcom

[SITE INTRO][5] Organizing Life / Why Use Project Management @
TheCenterOfTheNet.com ?
http://thecenterofthenet.com/faq/site-intro5-organizing-
life-why-use-project-management-thecenterofthenetcom
============================================================
=================
TheCenterOfTheNet.com @ Facebook
https://www.facebook.com/thecenterofthenet

TheCenterOfTHeNet.com @ Twitter
https://twitter.com/RobertPEatonJr

TheCenterOfTHeNet @ Youtube
https://www.youtube.com/channel/UCKw48xCg06QJYJ0qCeXew_A

**Comment by gufoe** [comment]
This bug is not related to the extension, but to the version of translate-shell we are using.
I just apt purged the old translate-shell and upgraded it manually as described [here](https://github.com/soimort/translate-shell), and it works perfectly :)
