### ISSUE TITLE
Styling is off a bit

### ISSUE THREAD

**Issue by Eimis-dev** [gufoe/text-translator#15]
The translation window is a bit messed up, and changing the size of the window doesn't help to fix it, can I do something to solve this?

Gnome shell version 3.26.1 (Ubuntu 17.10)

[Smaller window](https://image.ibb.co/hrPwbR/Screenshot_from_2017_10_27_18_43_02.png)
[Bigger window](https://image.ibb.co/ja6gAm/Screenshot_from_2017_10_27_18_40_36.png)

WONDERFUL extension by the way!

**Comment by gufoe** [comment]
Yes! I just pushed a few changes today, I've got one person to test it, but if you could try it aswell it would be awesome! To test the new changes:
```
cd ~/.local/share/gnome-shell/extensions
rm -rf text_translator@awamper.gmail.com
git clone https://github.com/gufoe/text-translator.git text_translator@awamper.gmail.com
```
Then press `alt`+`f2`, type `r` to reload the shell. Can you tell me if anything is wrong? I know there are some glitches, I've spent some time trying to fix them, but couldn't, so I guess they'll stay for now.

**Comment by Eimis-dev** [comment]
Oh nice!! It did make a difference, now window is nicely placed! Thank you!

[After update](https://image.ibb.co/dfi8O6/Screenshot_from_2017_10_27_19_48_22.png)

I didn't notice any other glitches, all other functions this tool provides works perfectly fine on my OS! I'm not a coder though, so chances are I don't know how to recognize the glitch!

**Comment by gufoe** [comment]
Great, I'll send the update to gnome now!
Thanks for the feedbak!
