### ISSUE TITLE
Error: can't convert length to an integer

### ISSUE THREAD

**Issue by caseca** [gufoe/text-translator#16]
Ubuntu: 16.04
Gnome-shell: 3.20.4
Error:
Gjs-Message: JS LOG: Extension "text_translator@awamper.gmail.com" had error: Error: can't convert length to an integer

When:
After upgrade text-translator

**Comment by gufoe** [comment]
Can you update the extension now and tell me if it works?

**Comment by caseca** [comment]
Error continue. 
I update the Text Translate through the gnome extensions page.

**Comment by caseca** [comment]
Pelo jeito suas atualizações fizeram com que a extensão não funcionasse mais no Gnome 3.20, e você nem se preocupou em manter a versão que funcionava no site, saiu alterando no master mesmo e atualizando tudo para a última versão.
Isso é muito triste, eu usava muito essa extensão e agora fiquei na mão.
Muito obrigado por nada.
PS: Coloquei em português mesmo, use a extensão para entender o que estou dizendo.
