### ISSUE TITLE
Default translation provider is always Yandex

### ISSUE THREAD

**Issue by itssvet** [gufoe/text-translator#17]
Hi,
Unfortunately I see little annoying bug in the latest update only, if update it from github or from extensions.gnome.org: the default translation source is always Yandex. Yes, I could switch it manually every time I press `Win+T` to open this extension, but it's not very comfortable.

I tried:
* to choose the default source at Preferences of text-translator directly,
* to change it by gnome-tweak-tools (the same, as I see),
* to reinstall extension from github \ from gnome.org,
* reboot gnome and PC,
* `remember the last used language` (I hoped for the miracle, huh).
And when I press `Win+T` again, I always see Yandex as a source.

Could you fix it please?
Thanks

**Comment by gufoe** [comment]
I see, I have the opposite thing happening, and I have google and it's impossible to set yandex as default.
I have tweaked some time with it but I couldn't fix it. I'll update this as soon as possible.
The number of side effects this code produces is just incredible. You fix something here and it breaks something elsewere, just wtf.

**Comment by itssvet** [comment]
Okay, thank you
