### ISSUE TITLE
Text Translator not installed

### ISSUE THREAD

**Issue by erhanbicer** [gufoe/text-translator#22]
Hello,
The Chrome plugin does not load the plugin by writing the following text.

> SyntaxError: JSON.parse: expected double-quoted property name
> 
> Stack trace:
>   TranslationProviderPrefs<._load_prefs@/home/erhan/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translation_provider_base.js:107
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   TranslationProviderPrefs<._init@/home/erhan/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translation_provider_base.js:100
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
>   Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
>   TranslationProviderBase<._init@/home/erhan/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translation_provider_base.js:219
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   _parent@resource:///org/gnome/gjs/modules/lang.js:131
>   Translator<._init@/home/erhan/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translation_providers/google_translation_provider.js:13
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
>   Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
>   TranslatorsManager<._load_translators@/home/erhan/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translators_manager.js:37
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   TranslatorsManager<._init@/home/erhan/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translators_manager.js:18
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
>   Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
>   TextTranslatorPrefsWidget<._get_main_page@/home/erhan/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/prefs.js:576
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   TextTranslatorPrefsWidget<._init@/home/erhan/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/prefs.js:546
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   buildPrefsWidget@/home/erhan/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/prefs.js:703
>   Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>   main@resource:///org/gnome/shell/extensionPrefs/main.js:397
>   @<main>:1
>

**Comment by arg1998** [comment]
same issue

**Comment by gufoe** [comment]
Can you try the patch I just made 3f8588f? You can apply it by executing the following command and then restarting the shell (`ALT+F2 -> r` or by logging out and in again)
`curl https://raw.githubusercontent.com/gufoe/text-translator/master/translation_provider_base.js > ~/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translation_provider_base.js`
