### ISSUE TITLE
Suddenly on multiple systems in 17.10 highlighting text to translate stopped working : (

### ISSUE THREAD

**Issue by AntiNSA** [gufoe/text-translator#25]
Id love to get it working again I use it quite often teaching. Thanks if you know...

**Comment by AntiNSA** [comment]
it can translate, however only if I paste the text to translate. highlighting the text and then using the shortcut to open the translation no longer works...

**Comment by AntiNSA** [comment]
Paste works, I am useing xorg and not wayland..... just highlighting the text and have it appear to be translated without pasting no longer works... In addition the translation box shifts/moves up and down about 10 pixels when open... like some sort of glich...

**Comment by gufoe** [comment]
It is still working for me (Debian with Gnome 3.26.2), I have no clue on why it is not working.
Any errors in lg? (alt+f2 -> lg -> extensions).

**Comment by AntiNSA** [comment]
my mistake... Even after using for so long somehow I forgot super+alt+t ...I perhaps am getting Alzheimers and losing my memory with old age............ It still works great...

**Comment by gufoe** [comment]
Well good luck with that! Happy to hear it's not one more new bug. As for the glitch when opening, I know, it's annoying, I've tried to fix it and I failed.
Cheers :)
