### ISSUE TITLE
I'm getting "Error: Requiring Clutter, version none: Typelib file for namespace [...]" when running prefs

### ISSUE THREAD

**Issue by mattalxndr** [gufoe/text-translator#28]
I'm on a fresh minimal install of Ubuntu 18.04, which uses Gnome Shell Shell 3.28.3.

![screenshot from 2018-09-10 15-18-59](https://user-images.githubusercontent.com/250466/45317061-37cb3000-b50f-11e8-9963-e0c1334aa25c.png)

**Comment by mattalxndr** [comment]
I checked out this similar issue:
https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/456

Running this will fix:
```
sudo apt install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0
```

**Comment by gufoe** [comment]
Thanks @mattalexx for the fix, closing this

**Comment by mattalxndr** [comment]
In my opinion, this bug should not be closed just because there's a workaround. Maybe you could add a dependency? Some documentation?

**Comment by gufoe** [comment]
Sure, I'll put it in the readme here and on the extension site, as extensions have no dependency management form what I know

**Comment by mattalxndr** [comment]
Oh I see. Thanks for explaining that to me.
