### ISSUE TITLE
regression in Gnome Shell 3.30 (arch linux) 

### ISSUE THREAD

**Issue by ccb23** [gufoe/text-translator#29]
SyntaxError: missing ( after for

**Comment by XolotlP** [comment]
In [language_chooser.js at line 228](https://github.com/gufoe/text-translator/blob/master/language_chooser.js#LC228)  the use of for `each...in` statement is [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for_each...in). 
Just replace `for each(let code in keys)` to `for (let code of keys)` and restart the extension or the shell

**Comment by ccb23** [comment]
nice, that works perfectly!
