### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by cclienti** [gufoe/text-translator#3]
Hello,

I wonder if there is a possibility to support the general proxy settings of gnome. These information can be forwarded to translate-shell (for the google provider).

Translate shell Networking options:
    -x HOST:PORT, -proxy HOST:PORT
        Use HTTP proxy on given port.

I think we can add the proxy option in google_translation_provider.js around line 300.

**Comment by gufoe** [comment]
[This](https://github.com/gufoe/text-translator/blob/issue-3/translation_providers/google_translation_provider.js) patch should detect and use the http proxy, please let me know if it works!

**Comment by cclienti** [comment]
Many thanks, it works :)

**Comment by gufoe** [comment]
You're welcome, I'm going to update the extension then :)
