### ISSUE TITLE
does not work in ububntu 18.10

### ISSUE THREAD

**Issue by Vladislavuz** [gufoe/text-translator#31]
Error: Please make sure both gawk and translate-shell are installed. Error: GLib.SpawnError: Не удалось выполнить процесс-потомок «trans» (Нет такого файла или каталога)
![2018-12-06 08-12-18](https://user-images.githubusercontent.com/30505454/49562950-bbd65d80-f92e-11e8-920e-061364ad39a2.png)

**Comment by lightway82** [comment]
+1

**Comment by roadsapsan** [comment]
нужно установить translate-shell ( sudo apt install translate-shell )
потом проверить установлены следующие зависимости:
sudo apt install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0

А вообще лучше читайте мануалы

**Comment by Vladislavuz** [comment]
> нужно установить translate-shell ( sudo apt install translate-shell )
> потом проверить установлены следующие зависимости:
> sudo apt install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0
> 
> А вообще лучше читайте мануалы

Я человек простой: устанавливаю прогу одним кликом

**Comment by gufoe** [comment]
Hi @vladislavyuzbekov did you fix the problem installing the `translate-shell` package?
