### ISSUE TITLE
While having focus on Text Translator using invocation Ctrl + Alt + Tab, that one cannot be launched

### ISSUE THREAD

**Issue by Ricky-Tigg** [gufoe/text-translator#33]
Component: gnome-shell.x86_64 3.30.2-1.fc29 @updates; Installed extension: _Text translator_.

Invoke keys _Ctrl_ + _Alt_ + _Tab_, select _Top Bar_, focus on _Text Translator_ icon, then press either _space_ key or _Return_ key.

![gnome-shell_3 30 2_text-translator](https://user-images.githubusercontent.com/26058215/53655867-be0c3780-3c51-11e9-9e41-89a1c27a4fd3.png)

Result: application isn't launched , however those keys invocations are able to launch panel related to icons-group dedicated to _GNOME_ – located on on its right side –.

**Comment by gufoe** [comment]
The shortcut should be Super+T actually, closing as nobody else seems to have the problem.
