### ISSUE TITLE
Translation with google translator does not work

### ISSUE THREAD

**Issue by dbogdanov** [gufoe/text-translator#4]
The right panel is empty. Yandex translation works.

**Comment by gufoe** [comment]
Thanks of the feedback, you have translate-shell installed, right?
What version of this extension do you have?
You can find out with `grep '"version"' ~/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/metadata.json`

**Comment by dbogdanov** [comment]
```
"version": 23
```

translate-shell is installed

**Comment by gufoe** [comment]
One last check, can you please open Looking Glass (`Alt + F2`, type `lg`, then return) and check if the extension has emitted any errors in the "extensions" tab?

**Comment by dbogdanov** [comment]
No errors

**Comment by gufoe** [comment]
I'm sorry but I'm not able to understand what might be causing your problem and I haven't been able to reproduce it.

**Comment by dbogdanov** [comment]
By the way, I can click on audio to hear the original phrase to translate.  When clicking Go, or on Ctrl-Enter, there is a text "Translating..." for a while and then nothing happens: no text, no audio with translation.

**Comment by MatLeb** [comment]
Same problem.
"version": 23
translate-shell is installed
No errors

**Comment by jaro3** [comment]
same problem, audio works, right window always shows "ftpPassword"
(I have to go through proxy)
trans from command line works fine!

**Comment by ghost** [comment]
`sudo apt-get install translate-shell`
this have fixed the problem in my case

**Comment by gufoe** [comment]
I think #8 fixed the problem, can somebody update manually and confirm?

**Comment by dbogdanov** [comment]
I've installed translate-shell with no success. 

#8 is related to special characters. I have an issue even without having them.

**Comment by gufoe** [comment]
Hey @dbogdanov, is it still broken?

**Comment by dbogdanov** [comment]
I've updated the extension via the gnome extension manager, but it still does not work.

**Comment by oldiob** [comment]
Same problem here. tanslate-shell version 26. I changed from google translate engine to the yandex engine. It seems to fix the problem for now. Perhaps google translate API changed? Great extension by the way!

**Comment by kyuden** [comment]
Same problem here.

**Comment by itssvet** [comment]
The same, on the 2nd PC, suddenly Google translator started to show only empty field, but Yandex works
Fedora 26, Gnome 3.24
:(
`Translate-shell` reinstall didn't help, but it works fine at the Terminal even using `google`
Extension reinstall from `http://extensions.gnome.org/` also didn't help.
No errors in `lg`.
Extension `"version": 26`.

What could I perform for further investigation? I really enjoy using this extension, but Yandex's translation is awful :)

**Comment by gufoe** [comment]
Hi, what's your translate-shell version (`trans --version`)?

**Comment by dbogdanov** [comment]
Translate Shell       0.9.2.1-git:f858086

**Comment by gufoe** [comment]
As written in the readme:

Make sure your version of translate-shell is over 0.9.5-1, otherwise it might cause issues.

I suggest you to uninstall your current version and to install manually the latest version:

```
wget git.io/trans
chmod +x ./trans
sudo mv trans /usr/bin/
```

**Comment by itssvet** [comment]
Hi,

```
$ trans --version
Translate Shell       0.9.6.4

platform              Linux
gawk (GNU Awk)        4.1.4
fribidi (GNU FriBidi) 0.19.7
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]
```

**Comment by itssvet** [comment]
Dear all-knowing wizard @gufoe, please tell us something else :)

**Comment by gufoe** [comment]
@dbogdanov, did updating translate-shell fix your problem?
@itssvet, you have everything setup correctly, so I'm working on a patch which should solve all of these bugs once and for all, stay ready as you'll be the beta tester!

**Comment by itssvet** [comment]
Okay, looking forward for it! Thanks!

**Comment by gufoe** [comment]
I've just pushed the last changes, you can try by:
```
cd ~/.local/share/gnome-shell/extensions
rm -rf text_translator@awamper.gmail.com
git clone https://github.com/gufoe/text-translator.git text_translator@awamper.gmail.com
```
Then press `alt`+`f2`, type `r` to reload the shell, and let me know if it works.
Also, apart minor bugs, the graphics should match the shell theme. Does it?

**Comment by itssvet** [comment]
My admiration! It works! Thank you!

**Comment by gufoe** [comment]
Great! I'm finally closing this, thanks everybody for the reports and the patience!

**Comment by dbogdanov** [comment]
@gufoe Thanks for the update! Did you also update the extension on extensions.gnome.org? I've just tried to install from there and now I get "Error loading extension" in Gnome Tweak Tool.

**Comment by itssvet** [comment]
@dbogdanov yesterday my Gnome updated this extension from extensions.gnome.org automatically, it works fine
UPD haha got the same error :(

**Comment by gufoe** [comment]
Hi guys, sorry for the delay, I was far from the pc last week. Luckily https://github.com/gufoe/text-translator/pull/20 should be fixing this! I'm uploading the extension now, I'll let you know when they approve it.
