### ISSUE TITLE
Tag/release version

### ISSUE THREAD

**Issue by ericdallo** [gufoe/text-translator#43]
Congratulations for the project!

I'm adding this project on [gnomeExtensions on NixOS](https://github.com/NixOS/nixpkgs/tree/master/pkgs/desktops/gnome-3/extensions), but I need a version or tag for this repository, what about tag some version or generate a release?
https://help.github.com/en/enterprise/2.18/user/github/administering-a-repository/managing-releases-in-a-repository

Thank you!

**Comment by gufoe** [comment]
The release is published!
