### ISSUE TITLE
The list of languages is not displayed

### ISSUE THREAD

**Issue by lwbaqueros** [gufoe/text-translator#54]
I am on a fresh installation of Ubuntu 20.10. When I want to select the languages, either in the `form` or `the target`, it does not display the list of possibilities. Only, English and Russian are by default, and actually, it works.
I have installed the following packages: translate-shell, gir1.2-clutter-1.0, gir1.2-clutter-gst-3.0, gir1.2-gtkclutter-1.0

![image](https://user-images.githubusercontent.com/46763074/100344111-a0176680-2fe0-11eb-83ae-af81da9644d9.png)

**Comment by rcsm17** [comment]
I found out a workaround to make this extension working. Just go to the extension settings and put your target language and then disable the flag "remember last used languages".

**Comment by lwbaqueros** [comment]
It works

**Comment by lham72** [comment]
Thanks so much !!
