### ISSUE TITLE
Translation with Google Translator doesn't works

### ISSUE THREAD

**Issue by juangl** [gufoe/text-translator#6]
I saw an related issue. I just want to add that I'm getting another error message.

`
Error executing translate-shell: GLib.SpawnError: Failed to execute child process "trans" (No such file or directory)`
![screenshot from 2017-01-08 19-11-58](https://cloud.githubusercontent.com/assets/1887029/21755247/616ac976-d5d6-11e6-82bf-f1cfdc1c3a94.png)

I'm running Archlinux.

**Comment by juangl** [comment]
also it made my session crash. After installing this extension I cannot log in anymore. 

I don't know where to find a log.

**Comment by gufoe** [comment]
Hello, seems like you don't have the `translate-shell` package, have you installed it through apt-get or equivalent?

**Comment by juangl** [comment]
Thank you. You're right. I see the `** Needs the package translate-shell **`.
