### ISSUE TITLE
special symbols stop translation

### ISSUE THREAD

**Issue by AntiNSA** [gufoe/text-translator#8]
Whenever translating something with the & symbol there is no translation...

**Comment by gufoe** [comment]
Thank you, I [found and fixed](https://github.com/gufoe/text-translator/commit/f29fe22e9e433a29dcca12be76b60803e144cd96) the bug which should finally solve the other issues people reported!
I just pushed the changes, and will update the extension soon.
You can update it manually now to check if it works by running:
```bash
curl https://raw.githubusercontent.com/gufoe/text-translator/f29fe22e9e433a29dcca12be76b60803e144cd96/translation_providers/google_translation_provider.js > ~/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translation_providers/google_translation_provider.js
```
