### ISSUE TITLE
extension doesn't work with gnome 3.24

### ISSUE THREAD

**Issue by philipraets** [gufoe/text-translator#9]
Unfortunately this great extension doesn't work with gnome 3.24

**Comment by AntiNSA** [comment]
Yes you are right and I really need this .. its one of my most important extensions. Can anything be done to make it work again?

**Comment by gufoe** [comment]
I don't have 3.24 yet, but I'll spin up a vm in the next days to check if I can do something about it

**Comment by AntiNSA** [comment]
Thats awesome if you could. I am a teacher in China and I use this all the time in Class and have really gotten to depend on it. ITs very useful. Thank you.

**Comment by AntiNSA** [comment]
PLease update this thread when you have the opourtunity to see if this can be done. The new gnome wprls so great for multiscreen/multi monitors. Id hate to downgrade, but if I have to go withoput the translation extension then I will most likely downgrade untill the extension is available.

**Comment by gufoe** [comment]
I downloaded ubuntu live, and this is the error I found with the extension:
```
Error: Requiring St, version none: Requiring namespace 'Clutter' version '0', but '1.0' is already loaded
 
Stack trace:
  @/home/ubuntu-gnome/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translation_providers/google_translation_provider.js:1:7
  TranslatorsManager<._load_translators@/home/ubuntu-gnome/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translators_manager.js:33:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  TranslatorsManager<._init@/home/ubuntu-gnome/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/translators_manager.js:15:29
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110:5
  Class.prototype._construct/newClassConstructor@resource:///org/gnome/gjs/modules/lang.js:213:20
  TextTranslatorPrefsWidget<._get_main_page@/home/ubuntu-gnome/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/prefs.js:576:35
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  TextTranslatorPrefsWidget<._init@/home/ubuntu-gnome/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/prefs.js:546:20
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  buildPrefsWidget@/home/ubuntu-gnome/.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/prefs.js:703:18
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:22
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
  x
 ```

**Comment by simonbcn** [comment]
same problem on Arch Linux with GNOME Shell 3.24.1

**Comment by gufoe** [comment]
I proposed the problem on [reddit](https://redd.it/66blsi) aswell, no answers. Hopefully I'll find a solution myself soon.

**Comment by AntiNSA** [comment]
Hey any progress on thus issue?

**Comment by AntiNSA** [comment]
this is erious..... lts and 16.10 are no longer supported by gnome & thus far insecure

**Comment by gufoe** [comment]
Still nothing, I'm sorry :(

**Comment by philipraets** [comment]
If I remove lines 828 till 832 in extension.js (it's the second let translate_label in function _add_topbar_buttons, there is an error that it is already declared), the extension somewhat works again in opensuse tumbleweed, I can translate things, but cannot open preferences, then I get the namespace error.

I don't have experience with debugging or writing gnome-shell extensions, so I don't know where to start.

**Comment by gufoe** [comment]
Nice, for some reason the `translate_label` was already defined and added previously at line 804, so I'm fixing this now, at the extension will be usable. As for the settings, I still don't know, but looking into it, good job @philipraets, thanks!

**Comment by gufoe** [comment]
Looks like just commenting the first two lines in `translation_providers/google_translation_provider.js` fixes the preferences bug, can somebody with 3.24 give it a try?

**Comment by philipraets** [comment]
just tested, and seems to work

**Comment by wnlima2** [comment]
Not Work on Gnome Debian 8.
Translate (ctrl + Enter) not work.
Go, not work

My test is English to Portuguese

**Comment by gufoe** [comment]
I've just tested on Ubuntu 17.04 with Gnome 3.24 and it's working, I'm closing the issue, thank you all.
